### ISSUE TITLE
Question about type casting from c_char

### ISSUE THREAD

**Issue by yrendykurniawan** [Thinkofname/steamworks-rs#12]
Hi, Im trying to add set rich presence `SteamAPI_ISteamFriends_SetRichPresence`
C header from SDK `virtual bool SetRichPresence( const char *pchKey, const char *pchValue ) = 0;`

My implementation:
`pub fn SteamAPI_ISteamFriends_SetRichPresence(instance: *mut ISteamFriends,  key: *const c_char, value: *const c_char) -> bool;`

```
    /// Set rich presence of current game.
    pub fn set_rp(&self, key: &str, value: &str ) -> Result<(), ()> {
        let key_rp = CString::new(key).unwrap();
        let val_rp = CString::new(value).unwrap();
       
        let success = unsafe { 
            sys::SteamAPI_ISteamFriends_SetRichPresence(self.friends, key_rp.as_ptr(), val_rp.as_ptr()) 
            
        };
        if success { Ok(()) } else { Err(()) }
    }
```

The question is, should `key_rp.as_ptr()` also cast using `as *const _` ? I saw some of your implementation using `as *const _`. If you dont mind to explain what `as *const _` do. 
I tried using `as *const _` and not using it, no compiler error.

**Comment by Thinkofname** [comment]
> If you dont mind to explain what as `*const _ do.`

`as *const _` Just casts but lets the compiler figure out the type pointer.

As for why: its not needed in this case, just a bad habit on my part. Its going from `os::raw::c_char` to `libc::c_char` but they should always be the same type for the most part.
