### ISSUE TITLE
Callbacks with async

### ISSUE THREAD

**Issue by wyozi** [Thinkofname/steamworks-rs#22]
Great library first of all! This actually makes working with steamworks quite pleasant. However, I'm facing some problems with the callback functions.

I would like to call e.g. UGC#create_item and then wait for the result. Since I will also need to poll for the results, it seems that using async future would be the best approach. However, if my knowledge of Rust guarantees is correct, the type of the callback function `FnMut` makes this quite difficult. 

I'm getting `cannot move out of 'sender', a captured variable in an 'FnMut' closure` with the code below. Since the Sender type should implement Copy, I don't think simple Arc Mutex tricks work here either. Would you have some quick tips whether this approach would be feasible?

```rust
use futures::Future;
use futures::channel::oneshot;
use futures::channel::oneshot::Canceled;
use std::pin::Pin;
use steamworks::{PublishedFileId, AppId, SteamError};
use futures::lock::Mutex;

type CreateResult = Result<(PublishedFileId, bool), SteamError>;
fn create<M>(ugc: &steamworks::UGC<M>, app_id: AppId) -> Pin<Box<dyn Future<Output = Result<CreateResult, Canceled>>>> {
    let (sender, receiver) = oneshot::channel::<CreateResult>();

    ugc.create_item(app_id, steamworks::FileType::Community, move|res| {
        sender.send(res).unwrap();
    });

    // TODO poll for receiver here

    return Box::pin(receiver);
}
```

**Comment by wyozi** [comment]
Here's a blocking non-future implementation I'm using. Maybe someone will find it useful.

```rust
type CreateResult = Result<(PublishedFileId, bool), SteamError>;
fn create<M: steamworks::Manager>(scl: &steamworks::SingleClient<M>, ugc: &steamworks::UGC<M>, app_id: AppId) -> CreateResult {
    let data = Arc::new(Mutex::new(None));
    
    {
        let c_data = data.clone();
        ugc.create_item(app_id, steamworks::FileType::Community, move |res| {
            let mut data = c_data.lock().unwrap();
            *data = Some(res);
        });
    }

    while data.lock().unwrap().is_none() {
        scl.run_callbacks(); 
        ::std::thread::sleep(::std::time::Duration::from_millis(100)); 
    }

    return data.lock().unwrap().unwrap();
}
```

**Comment by Thinkofname** [comment]
ah yeah. So callbacks (or as steam calls them) are built on top of what steam calls callbacks which are basically events. Because of this its possible to be called multiple times so `Fn` originally wouldn't have worked safely if something went wrong internally.  However with the new manual dispatch stuff it should be possible to change all the call results to `Fn` as this https://github.com/Thinkofname/steamworks-rs/blob/master/src/lib.rs#L176-L178 prevents duplicate calls from being an issue

**Comment by Thinkofname** [comment]
https://github.com/Thinkofname/steamworks-rs/commit/f0a4d2472820d5592cef9d3f4cb57c8ba17e5b2b Changed here, let me know if this helps.

**Comment by Seeker14491** [comment]
@Thinkofname changing callback arguments to take `Fn` instead of `FnMut` is more restrictive to the callers providing the closure. Did you mean to change them to `FnOnce` instead?

**Comment by Thinkofname** [comment]
yeah I think I did, whoops

**Comment by Thinkofname** [comment]
Changed here: https://github.com/Thinkofname/steamworks-rs/commit/8ded00a828d25e48bc0782e116c5e084cd42ecc3
