### ISSUE TITLE
Are all SDK operations supported?

### ISSUE THREAD

**Issue by sisso** [Thinkofname/steamworks-rs#27]
This crate doesn't have bindings for all the Steam SDK operations, right? At least, I can not find SteamEncryptedAppTicket_BDecryptTicket.

Are the methods added on demand by needs or are some well-defined boundaries that should be supported?

**Comment by Thinkofname** [comment]
The main crate only has things added generally when someone is willing to add them (via PR). The steamworks-sys (raw bindings) crate should contain most things although it seems to be missing that method, i'm guessing its not part of the flat api and needs to be included manually

**Comment by sisso** [comment]
Got it. You are right, the DecryptTicket is declared in ./public/steam/steamencryptedappticket.h

Thanks!
