### ISSUE TITLE
'SteamGameServer_Init': function does not take 6 arguments

### ISSUE THREAD

**Issue by Dmajster** [Thinkofname/steamworks-rs#28]
Hi,

I'm trying to run your example and when compiling I get this error

```
$ cargo run
   Compiling steamworks-sys v0.6.1
error: failed to run custom build command for `steamworks-sys v0.6.1`

Caused by:
  process didn't exit successfully: `D:\Repositories\rust_fps\game\target\debug\build\steamworks-sys-eb43cd0edde91b0b\build-script-build` (exit code: 1)
  --- stdout
  cargo:rustc-link-search=C:\SDKs\SteamworksSDK\redistributable_bin\win64
  cargo:rustc-link-lib=dylib=steam_api64
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-pc-windows-msvc")
  CXX_x86_64-pc-windows-msvc = None
  CXX_x86_64_pc_windows_msvc = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-pc-windows-msvc = None
  CXXFLAGS_x86_64_pc_windows_msvc = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "C:\\SDKs\\SteamworksSDK\\public/steam" "-W4" "-FoD:\\Repositories\\rust_fps\\game\\target\\debug\\build\\steamworks-sys-f499b415b8b3742f\\out\\src/lib.o" "-c" "src/lib.cpp"
  lib.cpp
  C:\SDKs\SteamworksSDK\public\steam\matchmakingtypes.h(45): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  C:\SDKs\SteamworksSDK\public\steam\matchmakingtypes.h(47): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  C:\SDKs\SteamworksSDK\public\steam\matchmakingtypes.h(161): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use 
_CRT_SECURE_NO_WARNINGS. See online help for details.
  C:\SDKs\SteamworksSDK\public\steam\matchmakingtypes.h(246): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  src/lib.cpp(52): error C2660: 'SteamGameServer_Init': function does not take 6 arguments
  C:\SDKs\SteamworksSDK\public\steam\steam_gameserver.h(102): note: see declaration of 'SteamGameServer_Init'
  exit code: 2

  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "C:\\SDKs\\SteamworksSDK\\public/steam" "-W4" "-FoD:\\Repositories\\rust_fps\\game\\target\\debug\\build\\steamworks-sys-f499b415b8b3742f\\out\\src/lib.o" "-c" "src/lib.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

**Comment by kaikalii** [comment]
I had same error a little while ago when I updated my version of the Steamworks SDK. The new version changed the number of arguments to a function, and this library doesn't account for it yet. I solved the problem by just downgrading my Steamworks, but it should probably be fixed. It probably wouldn't be that hard.

**Comment by Thinkofname** [comment]
ah, I haven't been following the latest releases and assumed the api would stay stable so I'm surprised they broke it. The hard part is deciding if we need to support the old sdk releases somehow or not. If we don't it'll be a major version bump on this crate too.

**Comment by kaikalii** [comment]
I just looked at the header for the new version of the SDK. Here is the culprit:
```c
inline bool SteamGameServer_Init( uint32 unIP, uint16 usGamePort, uint16 usQueryPort, EServerMode eServerMode, const char *pchVersionString );
```
Looks like they removed the `uint16 usGamePort` parameter, which was the second.

A major version bump is probably the thing to do I would think. Unless you could do something fancy dynamically checking the SDK version and then using the generated binding differently?

**Comment by Thinkofname** [comment]
tried to take a quick look with the new flat api stuff that was done on master and it seems like there are more breakages too. 

```
239   |             let utils = sys::SteamAPI_SteamUtils_v009();
      |                              ^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `SteamAPI_SteamUtils_v010`
```
The newer api versions some of the api call methods, so we'll have to version bump anyway to support that. Guess when thats done i'll have to document the required sdk version in the readme

**Comment by Thinkofname** [comment]
https://github.com/Thinkofname/steamworks-rs/commit/4d91f1939315d5eb9699fb8851156d8fa5c820e5

This now builds against v151. It didn't suffer from the `SteamGameServer_Init` issue. At some point i'll try and push a new version to crates.io when I have some free time to test it some more.

**Comment by kaikalii** [comment]
> [4d91f19](https://github.com/Thinkofname/steamworks-rs/commit/4d91f1939315d5eb9699fb8851156d8fa5c820e5)
> 
> This now builds against v151. It didn't suffer from the `SteamGameServer_Init` issue. At some point i'll try and push a new version to crates.io when I have some free time to test it some more.

Okay. Thanks a lot for this crate by the way. My game is written all in Rust, and this crate makes Steam integration extremely easy. I actually had some users experience issues with the Steam overlay, which is hopefully fixed in the new SDK version, so the ability to update will be good.

**Comment by Dmajster** [comment]
> 
> 
> [4d91f19](https://github.com/Thinkofname/steamworks-rs/commit/4d91f1939315d5eb9699fb8851156d8fa5c820e5)
> 
> This now builds against v151. It didn't suffer from the `SteamGameServer_Init` issue. At some point i'll try and push a new version to crates.io when I have some free time to test it some more.

Awsome, I'll test it out and see how it goes. Thank you again for such a propt response! You're awsome! :)

**Comment by Thinkofname** [comment]
Pushed `0.7.0` to crates.io. Hopefully everything works ok
