### ISSUE TITLE
cannot find function, tuple struct or tuple variant `SteamAPI_SteamUGC_v015` in crate `sys`

### ISSUE THREAD

**Issue by ffleader1** [Thinkofname/steamworks-rs#37]
I tried to compile the create with Steam SDK 151 but it gives me this

````
error[E0425]: cannot find function, tuple struct or tuple variant `SteamAPI_SteamUGC_v015` in crate `sys`
     --> C:\Users\fflea\.cargo\registry\src\github.com-1ecc6299db9ec823\steamworks-0.7.0\src\ugc.rs:666:36
      |
666   |                     let ugc = sys::SteamAPI_SteamUGC_v015();
      |                                    ^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `SteamAPI_SteamUGC_v014`
      | 
     ::: C:\Users\fflea\CLionProjects\rust_test\target\debug\build\steamworks-sys-1244e4b6e1e8ec01\out/bindings.rs:26893:5
      |
26893 |     pub fn SteamAPI_SteamUGC_v014() -> *mut ISteamUGC;
      |     -------------------------------------------------- similarly named function `SteamAPI_SteamUGC_v014` defined here
````
Does seem to be an updated function name issue. What should I do? Thank you.

**Comment by adumbidiot** [comment]
Are you sure you are using v151? When I grep for that function in v150 I get:
```
rg SteamAPI_SteamUGC_v014 .\steamworks_sdk_150\sdk\
.\steamworks_sdk_150\sdk\public\steam\steam_api_flat.h
649:S_API ISteamUGC *SteamAPI_SteamUGC_v014();

.\steamworks_sdk_150\sdk\public\steam\steam_api.json
9209:          "name_flat": "SteamAPI_SteamUGC_v014"
```
but in v151 I get:
```
rg SteamAPI_SteamUGC_v014 .\steamworks_sdk_151\sdk\
```
which is nothing.

**Comment by ffleader1** [comment]
> Are you sure you are using v151? When I grep for that function in v150 I get:
> 
> ```
> rg SteamAPI_SteamUGC_v014 .\steamworks_sdk_150\sdk\
> .\steamworks_sdk_150\sdk\public\steam\steam_api_flat.h
> 649:S_API ISteamUGC *SteamAPI_SteamUGC_v014();
> 
> .\steamworks_sdk_150\sdk\public\steam\steam_api.json
> 9209:          "name_flat": "SteamAPI_SteamUGC_v014"
> ```
> 
> but in v151 I get:
> 
> ```
> rg SteamAPI_SteamUGC_v014 .\steamworks_sdk_151\sdk\
> ```
> 
> which is nothing.
I just downloaded it so I am quite positive.
![image](https://user-images.githubusercontent.com/15016720/111713089-e5280880-881c-11eb-8d0a-0bbc487b9a09.png)
Isn't the problem seems to be starting within the crate, not my end, as it tried to call ````SteamAPI_SteamUGC_v015()```` instead of ````SteamAPI_SteamUGC_v014()````, which actually exists?

**Comment by adumbidiot** [comment]
The crate tried calling `SteamAPI_SteamUGC_v015()`, but only found `SteamAPI_SteamUGC_v014()`. Are you sure you set `STEAM_SDK_LOCATION` to the new v151 dir and restarted your terminal?

**Comment by ffleader1** [comment]
> The crate tried calling `SteamAPI_SteamUGC_v015()`, but only found `SteamAPI_SteamUGC_v014()`. Are you sure you set `STEAM_SDK_LOCATION` to the new v151 dir and restarted your terminal?

I even restarted my PC.
Where is this ````SteamAPI_SteamUGC_v014()```` located at?
I am checking my STEAM_SDK_LOCATION and yes, it shows ````SteamAPI_SteamUGC_v015```` in files like ````steam_api.json```` or ````steam_api_flat.h````.
Not sure if it's a cache problem or something, as I did have 150 installed, but I have already downloaded 151, change environment variable, and even restarted the PC.

**Comment by adumbidiot** [comment]
Try cleaning your project and rebuild it.

**Comment by ffleader1** [comment]
> Try cleaning your project and rebuild it.

Oh yeah I tried to delete the entire target folder and it can compile now.
However, the executable does not run
```
error: process didn't exit successfully: `target\debug\rust_test.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)
```
Do you by any chance know how to deal with this? Thank.

**Comment by adumbidiot** [comment]
You need to copy the `steam_api64.dll` into the same folder as your exe. You should be able to find it in `target\<release-type>\build\steamworks-sys-<hash>\out`.

**Comment by ffleader1** [comment]
> You need to copy the `steam_api64.dll` into the same folder as your exe. You should be able to find it in `target\<release-type>\build\steamworks-sys-<hash>\out`.

I also tried it but now I got it with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitFailed', src\main.rs:7:43
```
Sorry, I am very new to this 😢

**Comment by adumbidiot** [comment]
> Sorry, I am very new to this 😢

No worries

> I also tried it but now I got it with
> ```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitFailed', src\main.rs:7:43
> ```

That means that the game failed to connect to Steam. If I remember correctly, I think this can occur if there isn't a `steam_appid.txt` in the current working directory of the app when it isn't launched by Steam. This file just contains the number of your steam app. `480` is an id reserved by Steam for examples and testing, you can use that if you don't have an app id right now. [This repository actually uses this file in order to run tests](https://github.com/Thinkofname/steamworks-rs/blob/master/steam_appid.txt), so you can use that as an example.

**Comment by ffleader1** [comment]
> > Sorry, I am very new to this 😢
> 
> No worries
> 
> > I also tried it but now I got it with
> > ```
> > thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitFailed', src\main.rs:7:43
> > ```
> 
> That means that the game failed to connect to Steam. If I remember correctly, I think this can occur if there isn't a `steam_appid.txt` in the current working directory of the app when it isn't launched by Steam. This file just contains the number of your steam app. `480` is an id reserved by Steam for examples and testing, you can use that if you don't have an app id right now. [This repository actually uses this file in order to run tests](https://github.com/Thinkofname/steamworks-rs/blob/master/steam_appid.txt), so you can use that as an example.

Wow
Awesome.
Worked like a charm.
Thank you for your time.

**Comment by adumbidiot** [comment]
No problem
