### ISSUE TITLE
Steam Leaderboards support

### ISSUE THREAD

**Issue by Seeker14491** [Thinkofname/steamworks-rs#4]
I want to use the [Steam Leaderboards](https://partner.steamgames.com/doc/features/leaderboards) API to retrieve leaderboards for a game. It seems it isn't implemented in the `steamworks` crate, and there doesn't appear to be bindings for these functions in `steamworks-sys` either.

I suppose the first step in resolving this would be generating bindings for these functions; is there a reason bindings for these functions aren't being generated?

**Comment by Thinkofname** [comment]
Functions aren't currently automatically generated for the `-sys` crate, can't remember why exactly but it may have tripped up bindgen at the time. They are all listed manually here: https://github.com/Thinkofname/steamworks-rs/blob/44fa2974126bbcfd361d85dde2a55aeb50efe06d/steamworks-sys/src/lib.rs#L79

I should be able to wrap that API pretty quickly taking a glance at it but I don't use leaderboard in my game so testing may take a bit of work. I'll give it a go though

**Comment by Seeker14491** [comment]
Alright, thanks a lot; I'll try it out.

**Comment by Seeker14491** [comment]
It works! I'm able to fetch leaderboards with the `find_leaderboard` and `download_leaderboard_entries` functions.
