### ISSUE TITLE
Support Querying Workshop Content

### ISSUE THREAD

**Issue by Seeker14491** [Thinkofname/steamworks-rs#5]
I need support for [querying workshop content](https://partner.steamgames.com/doc/features/workshop/implementation#QueryContent), which is currently missing.

I could try working on this.

**Comment by Thinkofname** [comment]
> I could try working on this.

I don't have the workshop setup for my game currently (I plan to but much later than now). If you could work on this it would be great!

**Comment by Thinkofname** [comment]
This exists now (forgot to close this issue awhile ago)
