### ISSUE TITLE
Plans on supporting steam market and inventory trades?

### ISSUE THREAD

**Issue by arthurfiorette** [Thinkofname/steamworks-rs#75]
If not, do you have an idea of an existing crate that does that?

**Comment by ceifa** [comment]
I don't think this will ever be supported because it's not on the Steamworks SDK API.

**Comment by arthurfiorette** [comment]
Yeah, that's what I thought. 

Anyone knows any rust crate that interacts with steam market and/or inventory trades?

**Comment by ceifa** [comment]
Just searched for `steam` on `crates.io`:

https://crates.io/crates/steam-market-pricing
https://crates.io/crates/steam-trading
